package view;

public enum Output {
    INVALID_USER_NAME,
    INVALID_PASSWORD,
    SUCCESSFUL_LOGIN,
    SUCCESSFUL_REGISTER,
    INVALID_RESTAURANT_ID,
    SUCCESSFUL_SELECT_RESTAURANT,
    NO_ACTIVE_RESTAURANT,
    NO_SUCH_FOOD_TYPE_IN_RESTAURANT,
    NO_SUCH_FOOD_TYPE_IN_GENERAL,
    EQUAL_FOOD_TYPES,
    THERE_IS_ORDERS_WITH_THIS_FOOD_TYPE,
    FOOD_TYPE_EDITED,
    FOOD_TYPE_ALREADY_EXIST,
    FOOD_TYPE_ADDED,
}
