package view;

public enum RunOrders {
    CUSTOMER_MENU,
    DELIVERER_MENU,
    RESTAURANT_OWNER_MENU,
    RESTAURANT_MENU_USED_BY_OWNER,
    RESTAURANT_MENU_USED_BY_CUSTOMER,
    FOOD_MENU_USED_BY_OWNER,
    FOOD_MENU_USED_BY_CUSTOMER,
    LOGIN_MENU,

    EXIT,
}
